# Generated by Django 5.1.4 on 2024-12-12 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventary',
            new_name='Inventory',
        ),
    ]
